### ISSUE TITLE
Plugin breaks down when map size is not square

### ISSUE THREAD

**Issue by makspll** [marinaKollmitz/gazebo_ros_2Dmap_plugin#11]
See title, setting map to anything not square causes really weird glitching in the created map.

If you set an expansion limit to something like a 100 cells, you'll notice that multiple "wave-fronts" seem to be created.

**Comment by marinaKollmitz** [comment]
That is possible, I have not run this project in a while. It is possible that the scenenet branch has commits that fix the issue. I am not actively working on this project at the moment. I have been meaning to clean it up and bring it into a good shape since few people seem to be using it, but let's face it, I don't find the time right now. A pull request is appreciated and I will try to test and review it quickly. Thanks!
